name: Deployment on Heroku

on:
  workflow_dispatch:
    inputs:
      repository_name:
        description: slug of the repository to deploy
        required: true
      heroku_app_name:
        description: name of the app on Heroku
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository_name }}
      - uses: akhileshns/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
        with:
          heroku_app_name: ${{ github.event.inputs.heroku_app_name }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
